name: Docker Image CI

on:
  push:
    tags:
      - 'v*'

jobs:
  pre-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Pre build the Docker image
        uses: docker/build-push-action@v2
        with:
          target: builder
          context: ./modules/lfs-server
          push: false
          tags: gaalafis/lfs-server:builder

      - name: Save builder
        run: docker save -o builder-image.tar builder
        shell: bash

      - name: Upload Runtime Image
        run: |
          mv builder-image.tar ${{ runner.workspace }}/builder-image.tar
        shell: bash

  build:
    runs-on: ubuntu-latest
    needs: pre-build

    strategy:
      matrix:
        build: [-proxy-sbs, -proxy-sbs-locks-pg, -signer-sbs-locks-pg]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Restore Docker Build Cache
        uses: actions/cache@v2
        with:
          path: |
            /var/lib/docker/image
            /var/lib/docker/overlay2
            /var/lib/docker/containers
          key: docker-build-${{ runner.os }}-${{ hashFiles('**/Dockerfile*') }}
        if: always()

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: epigrapho/gaalafis-lfs-server
          tags: |
            type=semver,pattern={{version}}${{ matrix.build }}
            type=semver,pattern={{major}}.{{minor}}${{ matrix.build }}
            type=sha,suffix=${{ matrix.build }}

      - name: Download Build Image
        run: mv ${{ runner.workspace }}/build-image.tar build-image.tar
        shell: bash

      - name: Load Build Image
        run: docker load -i build-image.tar
        shell: bash

      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          target: runtime${{ matrix.build }}
          context: ./modules/lfs-server
          push: false
          tags: ${{ steps.meta.outputs.tags }}

# docker build ../modules/lfs-server -t "gaalafis/lfs-server:0.0.1-proxy-sbs" -f ../modules/lfs-server/Dockerfile --target=runtime_sbs_custom_signing
# docker build ../modules/lfs-server -t "gaalafis/lfs-server:0.0.1-proxy-sbs-locks-pg" -f ../modules/lfs-server/Dockerfile --target=runtime_sbs_custom_signing_locks
# docker build ../modules/lfs-server -t "gaalafis/lfs-server:0.0.1-signer-sbs-locks" -f ../modules/lfs-server/Dockerfile --target=runtime_main
# docker build ../modules/auth -t "gaalafis/gitolite:0.0.1" -f ../modules/auth/Dockerfile 
