name: E2E Tests

on:
  push:
    branches:
      - tests/e2e-tests

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run
      run: |
        echo "Running tests"
        cd tests
        ./build_and_test.sh
        echo "Tests passed"
