name: Integration Tests

on:
  push:
    branches:
      - tests/refactor-tests

jobs:
  test:
    runs-on: ubuntu-latest

    services:  
      bucket:
        image: minio/minio:edge-cicd
        env:
          MINIO_ACCESS_KEY: minio_access_key
          MINIO_SECRET_KEY: minio_secret_key
        ports:
          - "9000:9000"

      database:
        image: postgres:15.0
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: 1.70.0

      - name: Build and test
        run: |
          cd modules/lfs-server
          cargo build
          cargo test

  test-coverage: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup | Rust
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: 1.70.0

    - name: Install tarpaulin
      run: |
        cargo install cargo-tarpaulin

    - name: Generate code coverage
      run: |
        cd modules/lfs-server
        cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
